### ISSUE TITLE
DOM issue with dataReloadWithPromise example

### ISSUE THREAD

**Issue by anil21111981** [l-lin/angular-datatables#576] opened 2016-01-18 14:34 UTC
I am new to Angular JS datatable and I am using it in my project where I followed the example “dataReloadWithPromise” example to reload my data on the click of a  button.

But when ever I click on the button the DOM option changes automatically on first click the information hides and on the second click the pagination get hidden and the same behaviour can be replicated on the example given at http://l-lin.github.io/angular-datatables/#/dataReloadWithPromise

**Comment by l-lin** [comment] 2016-01-18 14:39
Duplicate of #549.

**Closed by l-lin** 2016-01-18 14:39 UTC
