### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by antoineabourjeilycme** [l-lin/angular-datatables#937] opened 2017-01-04 15:46 UTC
## Using:
- angular version: 2.4.1
- jquery version: 3.1.1
- datatables version: 1.10.13
- angular-datatables version: 2.0.1

Console log:
Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /node_modules/angular-datatables/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /node_modules/angular-datatables/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /node_modules/angular-datatables/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /node_modules/angular-datatables/node_modules/@angular/core/index.d.ts, resolving symbol DataTablesModule in /node_modules/angular-datatables/dist/angular-datatables.module.d.ts, resolving symbol DataTablesModule in /node_modules/angular-datatables/dist/angular-datatables.module.d.ts

https://github.com/angular/angular-cli/issues/3707

**Comment by antoineabourjeilycme** [comment] 2017-01-05 08:22
Update
When I used only ng build --dev without -aot I got
"ERROR in DataTablesModule is not an NgModule"

**Comment by l-lin** [comment] 2017-01-10 09:39
What's your `angular-cli.json` configuration? Can you show your Angular App code?

**Comment by antoineabourjeilycme** [comment] 2017-01-10 15:07
{
  "project": {
    "version": "1.0.0-beta.24",
    "name": "tods"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "",
      "mobile": false,
      "styles": [
        "../node_modules/uikit/dist/css/uikit.almost-flat.css",
        "styles.sass",
        "tods-theme.sass",
        "../node_modules/datatables.net-dt/css/jquery.dataTables.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/datatables.net/js/jquery.dataTables.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "sass",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

**Comment by l-lin** [comment] 2017-01-22 15:01
As mentionned in this [comment](https://github.com/l-lin/angular-datatables/issues/940#issuecomment-272491503), angular-datatables is compatible with angular-cli version 1.0.0-beta.21, newer versions are not certain.
I will not really fix this until angular-cli release a stable version.

**Comment by toniton** [comment] 2017-04-13 11:00
@angular/cli is stable at v1.0.0 now and i'm getting this error

`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider repla
cing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/mac/Documents/Projects/nodejs/fixershub
/node_modules/angular-datatables/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/mac/Documents/Projec
ts/nodejs/fixershub/node_modules/angular-datatables/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/mac/Documen
ts/Projects/nodejs/fixershub/node_modules/angular-datatables/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/mac/Do
cuments/Projects/nodejs/fixershub/node_modules/angular-datatables/node_modules/@angular/core/index.d.ts, resolving symbol DataTablesModule in /Us
ers/mac/Documents/Projects/nodejs/fixershub/node_modules/angular-datatables/src/angular-datatables.module.d.ts, resolving symbol DataTablesModule
 in /Users/mac/Documents/Projects/nodejs/fixershub/node_modules/angular-datatables/src/angular-datatables.module.d.ts`

**Comment by l-lin** [comment] 2017-04-16 22:06
Are you using angular 4? If so, then angular-datatables is still not compatible with version 4+.
Follow the issue #998 when it will be supported.

**Comment by pvanhemmen** [comment] 2017-06-13 11:11
Sorry to bring this problem up again, but with the latest angular-datatables (4.1.1) and the latest Angular Version (4.2.2) the problem still persists. Building for production throws the following slightly altered error:
```
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/paulvanhemmen/Sites/congreet/web/node_modules/angular-datatables/node_modules/@angular/core/core.d.ts, resolving symbol DataTablesModule in /Users/paulvanhemmen/Sites/congreet/web/node_modules/angular-datatables/src/angular-datatables.module.d.ts, resolving symbol DataTablesModule in /Users/paulvanhemmen/Sites/congreet/web/node_modules/angular-datatables/src/angular-datatables.module.d.ts
```
Anything I can do about it? Thanx!

**Comment by pvanhemmen** [comment] 2017-06-13 11:34
As a follow up, I was able to fix this issue by using the following workaround, see comment [here](https://github.com/angular/angular-cli/issues/3854#issuecomment-274344771) and [here](https://github.com/angular/angular-cli/issues/3854#issuecomment-299109237).

Just wondering if that's something completely out of range for implementation the angular-datatables Module?

**Comment by l-lin** [comment] 2017-06-13 13:08
Indeed. I'm checking.

**Comment by l-lin** [comment] 2017-06-13 15:46
Mmmh I seem to reproduce the issue with Node version 8.0.0 and NPM version 5.0.0.
However, with the previous version (Node 7.10.0 and NPM 4.2.0), I don't have any issue.

@pvanhemmen, what versions of Node and NPM are you using?

**Comment by pvanhemmen** [comment] 2017-06-13 20:24
Hey thanx for checking back.

On my dev machine I have

npm 4.2.0
nodejs v7.10.0

Nonetheless I get the same error on a different setup, where I have

npm 4.6.1
nodejs v6.10.2

Angular + CLI and angular-datatables are up to date:

angular/* 4.2.2
angular/cli 1.0.4
angular-datatables 4.1.1
typescript 2.3.2

Compiling settings are pretty straight forward as they are angular cli default values. If I can help with anything else, please let me know.

**Comment by fernandoTorresan** [comment] 2017-06-14 11:59
I have the same issue here:

`ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported.`

angular: 4.2.2
angular-datatables 4.1.1
typescript: 2.3.4

@angular/cli: 1.1.1
node: 8.1.0
os: linux x64

And i I discovered this issue in angular repository https://github.com/angular/angular/issues/15767

I think my project is specifically breaking because of the angular-datatables.module.d.ts

**Comment by fernandoTorresan** [comment] 2017-06-14 15:39
@pvanhemmen Your workaround worked for me, thank yout!

**Comment by minhthuan274** [comment] 2017-06-16 11:45
Thank you, you saved my life

**Comment by l-lin** [comment] 2017-06-18 15:07
Documentation added.

**Closed by l-lin** 2017-06-18 15:07 UTC
Labels: Angular, documentation

**Comment by nileshyadav326** [comment] 2017-06-18 16:25
don't  know why after adding above code my issue is not resolved for temporary I deleted the node_modue folder inside the angular-datatable folder and its works fine

**Comment by l-lin** [comment] 2017-06-19 08:10
@nileshyadav326, what was inside the node_modules folder?

What are the versions of the Node and NPM?

**Comment by nileshyadav326** [comment] 2017-06-19 10:55
npm version  5.0.1
node version 7.10.0
the node_module (angular-datatable/node_module) folder contain below folders
- @angular
- rxjs
- zone.js

**Comment by jeremybv89** [comment] 2017-10-18 00:46
Hello, does anyone know how to change the language?

**Comment by hirakagile** [comment] 2018-02-19 12:38
Hello, anyone faced following issue??
notsup Unsupported platform for fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.2.tgz: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
node version : 8.9.4
npm version : 5.6.0
Please help me out

**Comment by captainjaypee01** [comment] 2018-08-21 20:45
Can anyone help me on how to figure about the issue on not displaying the values in my datatables
I'm using latest angular cli version. There are no errors, it's just that the values are not showing in my table

**Comment by sivan-nsp** [comment] 2018-08-27 17:27
I am facing error after adding the above code 
error 

ERROR in ./src/main.ts
Module not found: Error: Can't resolve 'C:\Users\
ent\src'
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'C:\Users\
ent\src\app'
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'C:\Users\
ent\src\app'
ERROR in ./src/app/angular-material/angular-mater
Module not found: Error: Can't resolve 'C:\Users\
ent\src\app\angular-material'
ERROR in ./src/app/dashboard/dashboard.component.
Module not found: Error: Can't resolve 'C:\Users\
ent\src\app\dashboard'

**Comment by ag5593** [comment] 2018-09-10 16:59
I am facing problem of (click) event on FixedColumns in dataTable. When column is fixed or freeze angular click event does not work. However it works if column is not fixed or freeze. Anyone faced similar issue or knows solution for the same ?

**Comment by selvam326** [comment] 2018-12-23 14:34
how to apply colors in datatable.

**Comment by MishaBeskin** [comment] 2019-05-03 12:33
How correctly add language to table options  on Angular 7
thanks

**Comment by rehan13112** [comment] 2019-07-12 05:47
Good Mornings,

Does any body know how to add "pagination change event"?

Thanks in advance.

**Comment by kshankarcse** [comment] 2019-08-16 19:58
**Package.json**
{
  "name": "fruit",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.8",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "angular-datatables": "^8.0.0",
    "angular-font-awesome": "^3.1.2",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "datatables.net": "^1.10.19",
    "datatables.net-dt": "^1.10.19",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "ngx-toastr": "^9.1.0",
    "rxjs": "6.0.0",
    "save": "^2.3.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/cli": "~6.0.5",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/datatables.net": "^1.10.17",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.31",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.1",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}


**Version:**
node - v10.16.3
npm - v10.16.3
Angular CLI: 6.0.8
Node: 10.16.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.8.3


**Error**
_ERROR in node_modules/angular-datatables/node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/angular-datatables/node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/angular-datatables/node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected._

**Comment by MFahadMuzamil** [comment] 2019-10-26 06:51
I am facing problem data-table not workable. show me error console 
![39124076-afaf0404-4717-11e8-8cd0-af2f6176220e](https://user-images.githubusercontent.com/35959940/67615517-efd89c80-f7e6-11e9-975f-2116c21a906c.png)

**Comment by jayeshwasnik** [comment] 2020-04-09 18:50
@MFahadMuzamil downgrade you angular version to 8 or below.I think you are using angular 9.

**Comment by Saroj-K-Panda** [comment] 2020-05-31 02:59
Hello,
Is this data table can handle millions of records and with great performance in filtering as well.. Please reply.
Thanks in advance.

**Comment by Manishac12** [comment] 2020-09-04 06:18
I am facing problem data-table not workable. show me error console and im using angualr 8
9110 ERROR TypeError: table.DataTable is not a function
    at SafeSubscriber._next (merchant.component.ts:79)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:185)
    at SafeSubscriber.next (Subscriber.js:124)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
    at MapSubscriber.next (Subscriber.js:49)
    at FilterSubscriber._next (filter.js:33)
    at FilterSubscriber.next (Subscriber.js:49)
    at MergeMapSubscriber.notifyNext (mergeMap.js:69)

**Comment by faisalshafisit** [comment] 2020-11-27 10:39
> @MFahadMuzamil downgrade you angular version to 8 or below.I think you are using angular 9.

Can't downgrade. Too many complications. CDK plugin used which is incompatible with angular < 8

**Comment by faisalshafisit** [comment] 2020-11-27 10:40
> I am facing problem data-table not workable. show me error console and im using angualr 8
> 9110 ERROR TypeError: table.DataTable is not a function
> at SafeSubscriber._next (merchant.component.ts:79)
> at SafeSubscriber.__tryOrUnsub (Subscriber.js:185)
> at SafeSubscriber.next (Subscriber.js:124)
> at Subscriber._next (Subscriber.js:72)
> at Subscriber.next (Subscriber.js:49)
> at MapSubscriber._next (map.js:35)
> at MapSubscriber.next (Subscriber.js:49)
> at FilterSubscriber._next (filter.js:33)
> at FilterSubscriber.next (Subscriber.js:49)
> at MergeMapSubscriber.notifyNext (mergeMap.js:69)

Did you solve the issue?
