### ISSUE TITLE
Custom Button not working

### ISSUE THREAD

**Issue by Gajendrasinh** [l-lin/angular-datatables#454] opened 2015-09-24 05:10 UTC
This my code and my issue is that when i m use .fromFnPromise for call json at a time custom button is not working
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="http://cdn.datatables.net/plug-ins/1.10.8/features/searchHighlight/dataTables.searchHighlight.css" rel="stylesheet">
    
  </head>
  <body>
    <div ng-app="datatablesSampleApp">
      <div ng-controller="SimpleCtrl as showCase" class="code">
        <datatable-wrapper>
         <table datatable="" dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns" class="row-border hover"></table>
        <!--   <table datatable dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns"> -->
          </table>
        </datatable-wrapper>
      </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src="http://code.angularjs.org/1.3.13/angular.js"></script>
        <script src="js/angular-resource.min.js"></script>
    <script src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://rawgithub.com/l-lin/angular-datatables/v0.4.3/dist/angular-datatables.min.js"></script>

    <script type="text/javascript">
    angular.module('datatablesSampleApp', ['datatables', 'ngResource'])
  .controller('SimpleCtrl', SimpleCtrl)
  .directive('datatableWrapper', datatableWrapper)
  .directive('customBtn', customBtn);

function SimpleCtrl(DTOptionsBuilder, DTColumnBuilder, $resource, $interval, $http) {
  var vm = this;

 
 
  vm.dtOptions =DTOptionsBuilder.fromFnPromise(function() {
            return $resource('https://rawgit.com/l-lin/angular-datatables/master/data.json').query().$promise;
        })
    .withPaginationType('full_numbers')
  // Add your custom button in the DOM
    .withDOM('<"custom-btn">lftirp');

  vm.dtColumns = [
    DTColumnBuilder.newColumn('id').withTitle('ID'),
    DTColumnBuilder.newColumn('firstName').withTitle('First name'),
    DTColumnBuilder.newColumn('lastName').withTitle('Last name')
  ];

 
}



/**
 * This wrapper is only used to compile your custom button
 */
function datatableWrapper($timeout, $compile) {
  return {
    restrict: 'E',
    transclude: true,
    template: '<ng-transclude></ng-transclude>',
    link: link
  };

  function link(scope, element) {
    // Using $timeout service as a "hack" to trigger the callback function once everything is rendered
    $timeout(function () {
      // Compiling so that angular knows the button has a directive
      $compile(element.find('.custom-btn'))(scope);
    }, 0, false);
  }
}

/**
 * Your custom button
 */
function customBtn() {
  return {
    restrict: 'C',
    template: '<h1>Foobar</h1>'
  };
}
    </script>
  </body>
</html>
```

**Comment by l-lin** [comment] 2015-09-27 09:49
Duplicate of #402.
There is an existing example on [codepen](http://codepen.io/l-lin/pen/zGgGaV?editors=101) and I update my [example](http://l-lin.github.io/angular-datatables/#/angularDirectiveInDOM). I can't do more.

**Closed by l-lin** 2015-09-27 09:49 UTC

**Comment by ddxy** [comment] 2015-10-08 16:57
This does not work with datatable="ng", Any idea for a workaround?

**Comment by vmkumar** [comment] 2015-10-16 03:56
fromFnServerData  call time also custom button not displaying

**Comment by trajano** [comment] 2016-03-13 07:08
The problem I see is when you reach the timeout function the additional classes are not yet rendered.

   link: function (scope, element) {
       $timeout(function () {
           console.log(element.html()); // if you look at your console it does not have the whole table rendered yet.
           console.log(element.find('.custom-element)) // if you look at your console and expand it should show zero length data.
        }, 0, false);

**Comment by trajano** [comment] 2016-03-13 07:22
I think it needs to be bound with https://datatables.net/reference/option/initComplete somehow.

**Comment by trajano** [comment] 2016-03-13 07:59
I got it to work on my case, in a hacky sort of way.

I add this to my controller
<pre>
$('#user-datatable').on('draw.dt', function () {
   $compile($('.add-user-button'))($scope);
});</pre>

From what I can determine, the element for the table can be located using jQuery and the [`draw.dt`][1] event when it fires would have the toolbar elements already created as such I can locate the toolbar elements and compile them.

[1]: https://datatables.net/reference/event/draw
