### ISSUE TITLE
Using AngularJS directives with responsive plugin doesn't work for collapsed columns

### ISSUE THREAD

**Issue by n3v3rf411** [l-lin/angular-datatables#919] opened 2016-12-06 08:18 UTC
## What versions you are using?

- jquery version: 2.2.4
- datatables version: 1.10.12
- angular-datatables version: 0.5.5

## What's the problem?

Using angular directives with responsive plugin does not work for columns that are collapsed when the screen width is small. It does work fine though if the column is not yet collapsed. I checked the DOM and it seems that the responsive plugin recreates the column as a list and it seems to be not compiled. Here are the options that I am using:

## Can you share your code?

`.withOption('createdRow', row => this.$compile(angular.element(row).contents())($scope))
.withOption('responsive', true)
`

**Comment by l-lin** [comment] 2016-12-12 13:17
Duplicate of #209.

**Closed by l-lin** 2016-12-12 13:17 UTC
