### ISSUE TITLE
Broken with angular-cli: 1.0.0-beta.25.5

### ISSUE THREAD

**Issue by krishghata** [l-lin/angular-datatables#950] opened 2017-01-25 07:29 UTC
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

angular-cli: 1.0.0-beta.25.5
node: 6.9.2
os: win32 x64
@angular/common: 2.4.4
@angular/compiler: 2.4.4
@angular/core: 2.4.4
@angular/forms: 2.4.4
@angular/http: 2.4.4
@angular/platform-browser: 2.4.4
@angular/platform-browser-dynamic: 2.4.4
@angular/router: 3.4.4
@angular/compiler-cli: 2.4.4

## What's the problem?

facing this error on ng serve - 

ERROR in Error encountered resolving symbol values statically. Could not resolve
 angular-datatables relative to D:/Workshop/STS/RpCrm/angular/src/app/app.module
.ts., resolving symbol AppModule in D:/Workshop/STS/RpCrm/angular/src/app/app.mo
dule.ts, resolving symbol AppModule in D:/Workshop/STS/RpCrm/angular/src/app/app
.module.ts

ERROR in ./src/app/app.module.ts
Module build failed: Error: D:/Workshop/STS/RpCrm/angular/src/app/app.module.ts
(8,34): Cannot find module 'angular-datatables'.)
    at _checkDiagnostics (D:\Workshop\STS\RpCrm\angular\node_modules\@ngtools\we
bpack\src\loader.js:145:15)
    at D:\Workshop\STS\RpCrm\angular\node_modules\@ngtools\webpack\src\loader.js
:172:17
 @ ./src/main.ts 5:0-45
 @ multi main

## Can you share your code?

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule, XHRBackend, RequestOptions } from '@angular/http';
import { AppRoutingModule } from './app-routing.module';

import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { DataTablesModule } from 'angular-datatables';

import { SecureHttp }       from './_auth/secure-http';
import { AuthService }      from './_auth/auth-service.service';
import { CustomerService }  from './customer/customer.service';

import { AppComponent } from './app.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { LoginComponent } from './login/login.component';
import { ProfileComponent } from './profile/profile.component';
import { PageNotFoundComponent } from './page-not-found/page-not-found.component';
import { CustomerListComponent } from './customer/customer-list.component';
import { BusyModule } from './_commons/_busy/busy.module';

@NgModule({
  declarations: [
    AppComponent,
    DashboardComponent,
    LoginComponent,
    ProfileComponent,
    PageNotFoundComponent,
    CustomerListComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AppRoutingModule,
    NgbModule.forRoot(),
    DataTablesModule,
    BusyModule
  ],
  providers: [SecureHttp, AuthService, CustomerService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by l-lin** [comment] 2017-01-25 13:02
Duplicate of #937 and #940.

See my [comment](https://github.com/l-lin/angular-datatables/issues/937#issuecomment-274335910).

**Closed by l-lin** 2017-01-25 13:02 UTC
Labels: duplicate
