### ISSUE TITLE
ServerSide processing not working properly with ColumnFilter

### ISSUE THREAD

**Issue by joaocrq** [l-lin/angular-datatables#475] opened 2015-10-12 10:44 UTC
Hello,
I've a table with server-side processing and it works fine when I first load data, but when I try to use pagination or column filter it makes the request to the wrong url. If I disable column filter it works just fine...

**Example (with column filter enabled):**
- *First request*: `POST api/datatables/XXX (fine)`
- *Others*: `GET (current url)?params...`

**Example (without column filter enabled):**
- *First request*: `POST api/datatables/XXX (fine)`
- *Others*: `POST api/datatables/XXX (fine)`

Thanks in advance.

**Comment by l-lin** [comment] 2015-10-12 12:30
Duplicate of #467.

**Closed by l-lin** 2015-10-12 12:30 UTC

**Comment by joaocrq** [comment] 2015-10-12 15:34
Thanks, I've founded that issue/solution later. But now I'm with another problem. As I draw the columns dynamically there're 3 rows in header (one from dt, the other 2 written by me in the table's html, using ng-repeat). If I don't put any html only the column filters will show up, if I remove the ng-repeats and use static information it works pretty well, but I do not want that way... Is there any solution or hack I can make for it to work properly?

Thanks once again!

**Comment by l-lin** [comment] 2015-10-13 07:34
Can you share your code?

**Comment by joaocrq** [comment] 2015-10-13 07:51
Sure.

**Directive**:
```
module.exports = ['DTOptionsBuilder', 'DTColumnDefBuilder', '$http', function (DTOptionsBuilder, DTColumnDefBuilder, $http) {
    return {
        restrict: 'E',
        scope: {
            config: '=config'
        },
        controller: ['$scope', 'DTOptionsBuilder', 'DTColumnBuilder', function ($scope, DTOptionsBuilder, DTColumnBuilder) {
            let filters = [];
            
            if ($scope.config.columnFilters) { 
                for (var column in $scope.config.columns) {
                    var filter = {
                        type: $scope.config.columns[column].type
                    };

                    if ($scope.config.columns[column].type === 'select') {
                        let {type, filterValues, filterValuesProperty} = $scope.config.columns[column];
                        
                        if (filterValues) {
                            filter.values = $scope.config.columns[column].filterValues.map((data) => {
                                return data[filterValuesProperty];
                            });
                        } 
                    }

                    filters.push(filter);
                }
            }
            
            $scope.dtOptions = DTOptionsBuilder.newOptions()
                .withDataProp('data')
                .withOption('processing', true)
                .withOption('serverSide', true)
                .withFnServerData((sSource, aoData, fnCallback, oSettings) => {
                    $http.post('api/datatables/offices', {
                        start: aoData[3].value,
                        length: aoData[4].value,
                        draw: aoData[0].value,
                        order: aoData[2].value,
                        search: aoData[5].value,
                        columns: aoData[1].value                     
                    }).then((data) => {                        
                        fnCallback(data.data);                        
                    });
                })
                .withDisplayLength(5)
                .withBootstrap()
                .withBootstrapOptions({
                    TableTools: {
                        classes: {
                            container: 'btn-group tabletools-dropdown-on-portlet margin-r-101',
                            buttons: {
                                normal: 'btn btn-sm btn-table-portlet default',
                                disabled: 'btn btn-sm default disabled'
                            },
                            collection: {
                                container: 'DTTT_dropdown dropdown-menu tabletools-dropdown-menu'
                            }
                        }
                    }
                })
                .withTableTools('/assets/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf')
                .withTableToolsButtons([
                    { sExtends: 'copy', sButtonText: 'Copiar' },
                    { sExtends: 'print', sButtonText: 'Imprimir' },
                    { sExtends: 'collection', sButtonText: 'Guardar', aButtons: [
                        { sExtends: 'xls', sButtonText: 'Excel (.xls)' },
                        { sExtends: 'pdf', sButtonText: 'PDF (.pdf)' }
                    ]}
                ])
                .withColumnFilter({
                    sPlaceHolder: 'head:after',
                    aoColumns: filters ? filters : null
                });
            
            $scope.dtColumns = [];

            for (var column in $scope.config.columns) {
                if ($scope.config.columns.hasOwnProperty(column)) {
                    var col = DTColumnBuilder.newColumn($scope.config.columns[column].id).withTitle($scope.config.columns[column].title);

                    if ($scope.config.columns[column].hidden)
                        col.notVisible();

                    if ($scope.config.columns[column].unsortable)
                        col.notSortable();

                    if ($scope.config.columns[column].render)
                        col.renderWith($scope.config.columns[column].render);
                    
                    $scope.dtColumns.push(col);
                }
            }
        }],
        templateUrl: './views/table.html'
    };
}];
```

**Current View** (only showing column filters if any or correct headings if none):
```
<table datatable="" dt-options="dtOptions" dt-columns="dtColumns" dt-instance="dtInstance" class="table table-striped table-bordered dataTable dataTable-columnfilter table-hover responsive nowrap" style="width:100%"></table>
```

**Directive in use**:
```
<pol-datatable config="vm.tableConfig"></pol-datatable>
```

**tableConfig:**
```
{
    columnFilters: true,
    columns: [
        {id: 'id', type: 'number', title: 'ID', hidden: true},
        {id: 'name', type: 'text', title: 'Name'},
        {id: 'email', type: 'text', title: 'Email'},
        {id: 'country_id', type: 'select', filterValues: this.countries, filterValuesProperty: 'name', title: 'Country', render: (value, type, row) => {
            let country = api.static(
                {resource: 'countries', method: 'get', args: {
                    id: {property: 'country_id', value: value}
                }}
            );

            return country.name;
        }}
    ]
}
```
Although, if you have any other improvements to this code I'd appreciate! Thanks once again.

**Comment by l-lin** [comment] 2015-10-13 08:42
Here the code with multiple header using `ng-repeat`: http://codepen.io/l-lin/pen/wKqEjr?editors=101

I don't know if that answers your question or not though.

**Comment by joaocrq** [comment] 2015-10-13 09:48
Thanks for that snippet. I've changed my directive to use 'controllerAs' instead of directly using $scope which I thought it could help and because it's a better approach, but that doesn't made any difference to my problem. Your solution on the template (using `ng-repeat` in both `<tr />` and `<th />`) has worked as expected and fixed my problem, although I don't see it as a very good/solid solution because it feels more like a hack. I've refactored most of my directive's code, and here it is in case someone needs:

**Directive**
```
['DTOptionsBuilder', 'DTColumnDefBuilder', '$http', (DTOptionsBuilder, DTColumnDefBuilder, $http) => ({
    restrict: 'E',
    scope: {
        config: '=config'
    },
    controllerAs: 'vm',
    controller: ['$scope', 'DTOptionsBuilder', 'DTColumnBuilder', function ($scope, DTOptionsBuilder, DTColumnBuilder) {
        let vm = this;

        vm.config = $scope.config;

        // Datatables columns
        vm.dtColumns = vm.config.columns.map(column => {
            var col = DTColumnBuilder.newColumn(column.id).withTitle(column.title);

            if (column.hidden)
                col.notVisible();

            if (column.unsortable)
                col.notSortable();

            if (column.render)
                col.renderWith(column.render);

            return col;
        });

        // Datatables columns filters
        vm.dtColumnFilters = vm.config.columns.map(column => {
            if (!column.filter)
                return false;

            return column.filter;
        });

        // Datatables Options
        vm.dtOptions = DTOptionsBuilder.newOptions()
            .withDataProp('data')
            .withOption('processing', true)
            .withOption('serverSide', true)
            .withFnServerData((sSource, aoData, fnCallback, oSettings) => {
                $http.post('api/datatables/' + vm.config.endpoint, {
                    start: aoData[3].value,
                    length: aoData[4].value,
                    draw: aoData[0].value,
                    order: aoData[2].value,
                    search: aoData[5].value,
                    columns: aoData[1].value
                }).then((data) => {
                    fnCallback(data.data);
                });
            })
            .withDisplayLength(5)
            .withBootstrap()
            .withBootstrapOptions({
                TableTools: {
                    classes: {
                        container: 'btn-group tabletools-dropdown-on-portlet margin-r-101',
                        buttons: {
                            normal: 'btn btn-sm btn-table-portlet default',
                            disabled: 'btn btn-sm default disabled'
                        },
                        collection: {
                            container: 'DTTT_dropdown dropdown-menu tabletools-dropdown-menu'
                        }
                    }
                }
            })
            .withTableTools('/assets/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf')
            .withTableToolsButtons([
                { sExtends: 'copy', sButtonText: 'Copy' },
                { sExtends: 'print', sButtonText: 'Print' },
                { sExtends: 'collection', sButtonText: 'Save', aButtons: [
                    { sExtends: 'xls', sButtonText: 'Excel (.xls)' },
                    { sExtends: 'pdf', sButtonText: 'PDF (.pdf)' }
                ]}
            ])
            .withColumnFilter({
                sPlaceHolder: 'head:after',
                aoColumns: vm.dtColumnFilters ? vm.dtColumnFilters : null
            });
    }],
    templateUrl: './table.html'
})];
```

**View**
```
<table datatable dt-options="vm.dtOptions" dt-columns="vm.dtColumns" class="table table-striped table-bordered table-hover responsive nowrap" style="width:100%">
  <thead ng-if="vm.dtColumnFilters">
    <tr ng-repeat="header in [0, 1]" ng-hide="header === 1">
      <th ng-repeat="col in vm.config.columns" ng-if="!col.hidden">{{ col.title }}</th>
    </tr>
  </thead>
</table>
```

**Config**
```
{
    endpoint: 'offices',
    columns: [
        {id: 'offices_id', title: 'ID', filter: {
            type: 'text'
        }},
        {id: 'name', title: 'Name', filter: {
            type: 'text'
        }},
        {id: 'email', title: 'Email', filter: {
            type: 'text'
        }},
        {id: 'telephone', title: 'Telefone', filter: {
            type: 'text'
        }},
        {id: 'countries_id', title: 'País', filter: {
            type: 'select',
            values: countries.map(country => {
                return country.name_pt;
            })
        }, render: (value, type, row) => {
            let country = api.static(
                {resource: 'countries', method: 'get', args: {
                    id: {property: 'countries_id', value: value}
                }}
            );

            return country.name_pt;       
        }}
    ]
}
```

Thank you Louis!

**Comment by govindsah** [comment] 2015-12-07 08:33
Hi, Has anyone found a solution to the columnFilter issue? 

Thanks

**Comment by joterce** [comment] 2015-12-07 13:28
+1

**Comment by joaocrq** [comment] 2015-12-08 14:51
What exactly issue are you having, is it similar to mine? @joterce @govindsah

**Comment by govindsah** [comment] 2015-12-08 15:04
@joaocrq same issue you have reported initially.

Example (with column filter enabled):

First request: POST api/datatables/XXX (fine)
Others: GET (current url)?params...
Example (without column filter enabled):

First request: POST api/datatables/XXX (fine)
Others: POST api/datatables/XXX (fine)

**Comment by joterce** [comment] 2015-12-08 15:10
@govindsah I resolved it today using withFnServerData instead of ajax option

**Comment by govindsah** [comment] 2015-12-08 15:32
@joterce Can you please share your code as I have tried withFnServerData but didn't work.

Thanks

**Comment by govindsah** [comment] 2015-12-09 07:24
I have to set the sSource again after that it worked. Thanks @joterce

**Comment by idwebmedia** [comment] 2016-06-29 21:48
@joterce could you share your fix? I'm having the same issue

**Comment by heenat94** [comment] 2017-03-31 08:31
@govindsah could you please share your code? Facing the same issue. . .

**Comment by govindsah** [comment] 2017-12-22 13:01
@heenat94 - I am sorry, I missed your comment in my busy schedule.
