### ISSUE TITLE
remove row in fixed column table

### ISSUE THREAD

**Issue by paxmus** [l-lin/angular-datatables#699] opened 2016-04-25 13:56 UTC
Hi,
I use angular-datatables with ng-repeat to display rows. The two first rows are fixed withFixedColumns({leftColumns: 2}).

the function splice doesn't work to remove row. it doen't remove row's cells in fixed column.
how can I remove the row completely in this case (2 first columns are fixed) ?
Thanks

**Comment by l-lin** [comment] 2016-05-02 14:13
I can't reproduce your issue. Can you put it on a plnkr or something alike?

**Comment by paxmus** [comment] 2016-05-15 12:26
here is 
[https://plnkr.co/edit/69XCsJQ2ZaZypsMYtP4f?p=preview](https://plnkr.co/edit/69XCsJQ2ZaZypsMYtP4f?p=preview)

double click on row, remove it

**Comment by l-lin** [comment] 2017-11-25 15:09
Closing as issue is too old and the version is no longer maintained.

**Closed by l-lin** 2017-11-25 15:09 UTC
