### ISSUE TITLE
Is there an angular2 way for tables

### ISSUE THREAD

**Issue by alateefah** [l-lin/angular-datatables#948] opened 2017-01-19 14:30 UTC
## What versions you are using?
- angular version (cli): 1.0.0-beta.19-3
- jquery version: 3.1.1
- datatables version: 2.1.1
- angular-datatables version: 2.0.1

## What's the problem?
Table content is displayed and i still get  "No data available in table error". In angular 1, datatable="ng" solved my problem. This doesn't seem to work i angular 2.

## Can you share your code?

<table _ngcontent-fre-5="" class="table limitTable dataTable no-footer" datatable="" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
        <thead _ngcontent-fre-5="" class="thead-blue">
          <tr _ngcontent-fre-5="" role="row"><th _ngcontent-fre-5="" class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Event: activate to sort column descending" style="width: 124px;">Event</th><th _ngcontent-fre-5="" class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Period: activate to sort column ascending" style="width: 135.2px;">Period</th><th _ngcontent-fre-5="" class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Channel: activate to sort column ascending" style="width: 162.4px;">Channel</th><th _ngcontent-fre-5="" class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Limit: activate to sort column ascending" style="width: 114.4px;">Limit</th><th _ngcontent-fre-5="" class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Status: activate to sort column ascending" style="width: 131.2px;">Status</th></tr>
        </thead>
        <tbody _ngcontent-fre-5="">
          <tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">Transfer To International Bank</td>
              <td _ngcontent-fre-5="">Daily</td>
              <td _ngcontent-fre-5="">Web</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr><tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">BillPayment</td>
              <td _ngcontent-fre-5="">Daily</td>
              <td _ngcontent-fre-5="">Mobile</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr><tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">Recharge</td>
              <td _ngcontent-fre-5="">Daily</td>
              <td _ngcontent-fre-5="">Web</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr><tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">Any transaction</td>
              <td _ngcontent-fre-5="">Daily</td>
              <td _ngcontent-fre-5="">Web</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr><tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">Intratransfer</td>
              <td _ngcontent-fre-5="">Daily</td>
              <td _ngcontent-fre-5="">Any Channel</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr><tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">Intratransfer</td>
              <td _ngcontent-fre-5="">Daily</td>
              <td _ngcontent-fre-5="">Web</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr><tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">Intertransfer</td>
              <td _ngcontent-fre-5="">Daily</td>
              <td _ngcontent-fre-5="">Web</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr><tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">Selftransfer</td>
              <td _ngcontent-fre-5="">Daily</td>
              <td _ngcontent-fre-5="">Web</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr><tr _ngcontent-fre-5="" class="even">
              <td _ngcontent-fre-5="">Selftransfer</td>
              <td _ngcontent-fre-5="">Weekly</td>
              <td _ngcontent-fre-5="">Any Channel</td>
              <td _ngcontent-fre-5="">90 PER TRANSACTION</td>
              <td _ngcontent-fre-5="">ACTIVE</td>
          </tr>
        <tr class="odd"><td valign="top" colspan="5" class="dataTables_empty">No data available in table</td></tr></tbody>      
      </table>

```html
<table datatable="ng" class="table limitTable">
        <thead class="thead-blue">
          <tr>
              <th>Event</th>
              <th>Period</th>
              <th>Channel</th>                
              <th>Limit</th>
              <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let userLimit of userLimits"  [class.even]="'table-alt-color'">
              <td>{{userLimit.events}}</td>
              <td>{{userLimit.periods}}</td>
              <td>{{userLimit.channels}}</td>
              <td>{{userLimit.limitName}}</td>
              <td>{{userLimit.status}}</td>
          </tr>
        </tbody>      
      </table>
```

**Comment by adriangraf** [comment] 2017-01-19 15:06
If you use hte angular cli then you can try the following:

npm install jquery
npm install @types/jquery
npm install datatables.net

than add the javascript to your scripts block in the angular-cli.json file
"../node_modules/jquery/dist/jquery.js",
"../node_modules/datatables.net/js/jquery.dataTables.js",

After that it should be possible to call 
(<any>$('example')).dataTable();
in the ngOnInit or ngAfterViewInit

In the HTML the table should be marked with #example

**Comment by alateefah** [comment] 2017-01-19 16:08
Still shows data not available in table

**Comment by l-lin** [comment] 2017-01-22 16:16
angular-datatables v2.0.X still does not have any angular renderer. Thus you can't use it like this yet.

**Comment by matthewhegarty** [comment] 2017-01-23 22:02
Are there any plans to add the angular renderer?  Presumably this will stop many people from being able to use the library.
Is there a recommended way to populate the table with dynamic data?

**Comment by l-lin** [comment] 2017-01-24 08:15
Yes, I plan to do it. However, as I'm still trying to figure out the front stack... It might take a while.

**Comment by matthewhegarty** [comment] 2017-01-24 10:00
Excellent.  It's a promising library, and having Angular2 support will be an essential addition.

**Comment by l-lin** [comment] 2017-02-12 15:14
Duplicate of #955.

**Closed by l-lin** 2017-02-12 15:14 UTC
