### ISSUE TITLE
Version 1.5.7 of Angular Breaks Datatables

### ISSUE THREAD

**Issue by martinkoslof** [l-lin/angular-datatables#781] opened 2016-06-28 18:04 UTC
I updated my applications to version 1.5.7 of AngularJs today and DataTables no longer works.  After rolling back to version 1.4.8 of AngularJS everything works properly. I am using the newest distribution version of Datatables and Datatables Bootstrap integration (0.5.5).  I am also using version 1.10.9 of the JQuery Datatables plugin and JQuery 1.11.1.

**Comment by martinkoslof** [comment] 2016-06-28 18:17
As a follow up, if helpful, starting with version 1.5.1 of Angular I have this problem. Upgrading 1.4.8 to 1.5.0 works. Beyond this, all future versions break Datatables

**Comment by l-lin** [comment] 2016-07-04 13:36
I upgraded the vendors versions in the [documentation](http://l-lin.github.io/angular-datatables/#/angularWayWithOptions) and I can't reproduce the issue.

**Comment by martinkoslof** [comment] 2016-07-05 16:13
Well, it still isn't work for me :). I will try to create a plunkr or something of the like if I get a free moment. I have mimicked the entire example, even upgrading to JQuery 2.2.4 which I know isn't a part of the problem. If I use 0.5.5 databases release with anything above Angular 1.50 it does not work:

 Expected expression in form of "_item_ in _collection_[ track by _id_]" but got "{0}". at Object.render

**Comment by martinkoslof** [comment] 2016-07-05 16:22
OK, well this is my problem as well:

https://github.com/l-lin/angular-datatables/issues/746

For whatever reason, it didn't show itself until I upgraded beyond Angular 1.5 and used Datatables minified releases 0.5.5. Everything works if I comment out my debuginfo line:

//$compileProvider.debugInfoEnabled(false);

You should be able to easily reproduce this now. All my Angular applications have this set as false, so in order to use the newest vendor versions and Datatables I need to remove this which I don't want to do.

Thanks

**Comment by l-lin** [comment] 2016-07-05 16:27
Ok, thank you. Closing this issue as it's a duplicate of #746.

**Closed by l-lin** 2016-07-05 16:27 UTC
