### ISSUE TITLE
Combine server side and responsive not working

### ISSUE THREAD

**Issue by mariolope10** [l-lin/angular-datatables#1177] opened 2018-02-13 23:03 UTC
Hello,

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- angular-datatables version: last
- responsive-plugin
</code></pre>

## Current behavior

When I use the plugin responsive with server side, responsive not working. ¿Any help about this?. I have all the day trying resolve but is imposible. Sorry for my English.

Thank you.

**Comment by alewebcode** [comment] 2018-04-23 13:29
What is the forecast for an answer?

**Comment by jach58** [comment] 2018-12-07 22:57
Do you have any solution for this issue?

**Comment by l-lin** [comment] 2018-12-17 11:59
Duplicate of #1264.

**Closed by l-lin** 2018-12-17 11:59 UTC
Labels: Angular, Help wanted
