### ISSUE TITLE
Pagination message prob with angular way server side processing.

### ISSUE THREAD

**Issue by haritkumar** [l-lin/angular-datatables#1570] opened 2021-06-10 12:07 UTC
# :beetle: bug report

When we select All from the page size dropdown and send -1 as page length then pagination msg looks like 
Showing 1 to 0 of 10

It should be 1 to 10 of 10

## :8ball: Expected behavior

<pre><code>

</code></pre>

## :globe_with_meridians: Your Environment

- node version: 
- angular version: 
- angular-cli version: 
- jquery version: 
- datatables version: 
- angular-datatables version:

**Comment by shanmukhateja** [comment] 2021-06-10 15:06
Hi,

Page no -1 is an invalid input which is why the table is freaking out. This is an expected outcome and is not a bug per se. Please note this library is an Angular directive to the jQuery plugin. So if you still feel this is a bug, please report it to DataTables developers.

I'm closing this issue as there's nothing that can be done.

**Closed by shanmukhateja** 2021-06-10 15:06 UTC
Labels: bug
