### ISSUE TITLE
Does this support angular4? 

### ISSUE THREAD

**Issue by yunClouds** [l-lin/angular-datatables#1007] opened 2017-04-04 09:02 UTC
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 4.0.0
- jquery version: 
- datatables version:
- angular-datatables version:  2.3.0
- angular-cli version: "@angular/cli": "^1.0.0", （for angular4）
![image](https://cloud.githubusercontent.com/assets/26613310/24648901/cf752fa0-1957-11e7-9a37-620a7fc9f4f1.png)

## What's the problem?

Does this support angular4?  how to do , I update to angular 4, there has some problem with angular-datatables:

![image](https://cloud.githubusercontent.com/assets/26613310/24648678/f3e598e4-1956-11e7-992d-c8a2de8ef535.png)

## Can you share your code?

![image](https://cloud.githubusercontent.com/assets/26613310/24649007/2b47a74a-1958-11e7-856e-64c586833c27.png)

**Comment by l-lin** [comment] 2017-04-04 09:38
Duplicate of #998.

**Closed by l-lin** 2017-04-04 09:38 UTC
