### ISSUE TITLE
PagingType (full_numbers) and Buttons extension not working together

### ISSUE THREAD

**Issue by giant995** [l-lin/angular-datatables#1256] opened 2018-06-08 18:19 UTC
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

## Current behavior

When using the Buttons extension, it overrides the pagingType options (full_numbers) in the HTML view.  Both options can't be used at the same time. The pageLength option still works.

![image](https://user-images.githubusercontent.com/14026304/41173499-2d176450-6b25-11e8-96c3-020f9a5f03a7.png)

## Expected behavior

I would like to be able to use the buttons extension while having the ability to chose the number of rows to display. Is it something possible ? Let me know if it's a datatables.net thing.

## Minimal reproduction of the problem with instructions

> HTML:

```
<table datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger" 
class="row-border hover responsive">
  <thead>
    <tr>
        <th> Series </th>
        <th *ngFor="let element of elements">{{element.symbol}}</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let key of keys">
      <td>{{key}}</td>
      <td *ngFor="let cert of dataSourceCerts[key]">{{cert.precision === null ? '' : (cert.certifiedAvg | number: '1.' + cert.precision +'-'+ cert.precision)}}</td>
    </tr>
  </tbody>
</table>
```

> Typescript:

```
dtOptions: any = {};
dtTrigger: Subject<any> = new Subject();
ngOnInit() {
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 10,
      dom: 'Bfrtip',
      buttons: [
        'excel',
        'print'
      ]
    };
}
ngOnDestroy(): void {
    this.dtTrigger.unsubscribe();
}
```

## Environment

<pre><code>
- node version: 8.11.1
- angular version: 6.0.4
- angular-cli version: 6.0.8
- jquery version: 3.3.1
- datatables version: 1.10.16
- angular-datatables version: 6.0.0
</code></pre>

**Comment by jdmadriz** [comment] 2018-06-11 22:55
is this fixed?

**Comment by giant995** [comment] 2018-06-12 01:53
As of now, no this is still an issue (?)

**Comment by giant995** [comment] 2018-06-19 13:05
@l-lin is it possible to at least know if this is a problem with this project or it is from datatables.net. Thank you

**Comment by giant995** [comment] 2018-07-10 12:09
Sorry, I was not clear enough. It does it in your example too: The _Show n entries_ feature does not work when the export buttons are activated. 

This image shows what feature I am talking about:
![image](https://user-images.githubusercontent.com/14026304/42508885-244696aa-8418-11e8-860d-47c4d08f64a6.png)

This image, taken from your example, shows the _Show n entries_ feature disappearing when buttons are activated:
![image](https://user-images.githubusercontent.com/14026304/42508996-791f1968-8418-11e8-91bf-e4f879e42d5b.png)

So to reproduce this bug (?), all you have to do is active paging then activate any button from the _Buttons Extension_

**Comment by leonelngande** [comment] 2018-08-03 05:09
Experiencing this issue too, can this be fixed?

**Comment by ng-model** [comment] 2018-08-13 14:34
Experiencing the same issue !!

**Comment by neevany** [comment] 2018-08-22 09:27
you need to use `dom: 'Blfrtip'` for getting PagingType when you are using buttons extension. 
I've included `l` there, it stands for length changing input control.

See the docs for more info. https://datatables.net/reference/option/dom

**Comment by ng-model** [comment] 2018-08-22 11:15
Thanks @neevany We know that, but still the problem persists !!

**Comment by l-lin** [comment] 2018-08-25 15:58
I updated the [stackblitz](https://stackblitz.com/edit/pagingtype-and-buttons-1256) that include what @neevany has said.
I can't seems to reproduce your issue, or am I not understanding what the problem is? :thinking:

**Comment by giant995** [comment] 2018-09-05 00:09
Thanks for the update @ng-model

**Comment by ng-model** [comment] 2018-09-05 00:16
No problem, did it work for you ?? @giant995

**Comment by giant995** [comment] 2018-09-05 22:06
I will never know. This was for an internship and I don't work on the project anymore.

**Comment by ng-model** [comment] 2018-09-05 22:09
No problemo @giant995 Good luck and can you close the issue please.

**Closed** 2018-09-05 22:18 UTC
Labels: Angular
