### ISSUE TITLE
The angular-datatables with responsive plugin the .rendrerWith not working

### ISSUE THREAD

**Issue by atarason** [l-lin/angular-datatables#209] opened 2015-02-05 10:23 UTC
on mobile no render checkbox 

DTColumnBuilder.newColumn('hiring').withTitle('Hiring').notSortable().renderWith(function (data, type, full, meta) {
                        return data ? <input type="checkbox" disabled checked /> : <input type="checkbox" disabled />
;
                    }),

**Comment by l-lin** [comment] 2015-02-05 10:28
Duplicate of #204.

**Comment by l-lin** [comment] 2015-02-06 22:52
The problem must come from the Responsive plugin:
> The child row's for a collapsed table in Responsive, by default, show a `ul/li` list of the data from the hidden columns. The [`responsive.details.renderer`](http://datatables.net/extensions/responsive/reference/option/responsive.details.renderer) option provide the ability to create your own custom renderer. It is given two parameters: the DataTables API instance for the table and the row index to use.

Please see the [Responsive's documentation](http://datatables.net/extensions/responsive/examples/child-rows/custom-renderer.html) on how you can customize the row.

**Closed by l-lin** 2015-02-06 22:52 UTC
Labels: bug

**Comment by atarason** [comment] 2015-02-06 23:10
ok, thanks for information

**Comment by zoobe50** [comment] 2016-11-24 22:57
@l-lin
I am using angular-datatables - v0.5.5 and Responsive 2.0.2.
When I click on thumbs Up in child, ng-click don't work. I have modified my code as you mentioned in 
Below is my code , please advise

![example](https://cloud.githubusercontent.com/assets/22899669/20610922/615739e6-b2f5-11e6-8d08-94ef21f5a6cb.png)

@atarason any luck ???

**Comment by zoobe50** [comment] 2016-11-24 22:59
@l-lin
I am using angular-datatables - v0.5.5 and Responsive 2.0.2.
When I click on thumbs Up in child, ng-click don't work.
Below is my code , please advise

![example](https://cloud.githubusercontent.com/assets/22899669/20610953/cb67ece0-b2f5-11e6-9517-3cd0e460a143.png)

@atarason  any luck ??
