### ISSUE TITLE
Warning: Unable to fully load * for source-map flattening: ENOENT: no such file or directory, open *.map

### ISSUE THREAD

**Issue by Neizan-93** [l-lin/angular-datatables#1479] opened 2020-11-20 09:39 UTC
```
Warning: Unable to fully load _{{APP_ROOT}}/_/node_modules/angular-datatables/src/angular-datatables.directive.js for source-map flattening: ENOENT: no such file or directory, open '_{{APP_ROOT}}/_/node_modules/angular-datatables/src/angular-datatables.directive.js.map'
Warning: Unable to fully load _{{APP_ROOT}}/_/node_modules/angular-datatables/src/angular-datatables.module.js for source-map flattening: ENOENT: no such file or directory, open '_{{APP_ROOT}}/_/node_modules/angular-datatables/src/angular-datatables.module.js.map'
Warning: Unable to fully load _{{APP_ROOT}}/_node_modules/angular-datatables/index.js for source-map flattening: ENOENT: no such file or directory, open '_{{APP_ROOT}}/_/node_modules/angular-datatables/index.js.map'
```

**Comment by shanmukhateja** [comment] 2020-11-29 09:55
Duplicate of #1470

**Comment by shanmukhateja** [comment] 2020-11-29 11:27
This is not a duplicate. Updated the labels accordingly.

**Closed** 2021-01-03 13:44 UTC
Labels: Angular, Help wanted, Not respecting ISSUE_TEMPLATE, bug
