### ISSUE TITLE
(click) not working with Angular 4

### ISSUE THREAD

**Issue by LexBel-co** [l-lin/angular-datatables#1022] opened 2017-05-17 00:26 UTC
Hello...

I'm working with the lastest versions, and i have added a button per row with a (click) binder, but it does not work.

The button looks like this:
`<a class="btn btn-danger btn-fab" (click)="myFunction()"><i class="material-icons">block</i></a>`

Thank you in advance

**Comment by l-lin** [comment] 2017-05-17 20:40
Duplicate of #982.

**Closed by l-lin** 2017-05-17 20:40 UTC
