### ISSUE TITLE
getting below error

### ISSUE THREAD

**Issue by nileshyadav326** [l-lin/angular-datatables#1035] opened 2017-06-16 08:57 UTC
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /var/www/html/suryodaybank/ng2-admin-lte/node_modules/angular-datatables/node_modules/@angular/core/core.d.ts, resolving symbol DataTablesModule in /var/www/html/suryodaybank/ng2-admin-lte/node_modules/angular-datatables/src/angular-datatables.module.d.ts, resolving symbol DataTablesModule in /var/www/html/suryodaybank/ng2-admin-lte/node_modules/angular-datatables/src/angular-datatables.module.d.ts

below is my package.JSON attached

`{
  "name": "ng2-admin-lte",
  "version": "0.8.1",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve --host 127.0.0.1 --port 3000",
    "prod": "ng build --prod",
    "gen": "ng g",
    "pages": "ng github-pages:deploy",
    "version": "ng --version",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/cli": "1.0.0-beta.32",
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/router": "3.4.8",
    "admin-lte": "^2.3.8",
    "angular-datatables": "^4.1.1",
    "angular2-jwt": "^0.1.24",
    "angular2-toaster": "^1.0.2",
    "angular2-uuid": "^1.1.0",
    "angularfire2": "^2.0.0-beta.6",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "datatables.net": "^1.10.15",
    "datatables.net-dt": "^1.10.15",
    "firebase": "^3.6.6",
    "font-awesome": "^4.7.0",
    "ionicons": "^3.0.0",
    "jquery": "^3.2.1",
    "ng2-bootstrap": "^1.1.16",
    "ng2-translate": "^4.2.0",
    "rxjs": "^5.1.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@types/datatables.net": "^1.10.2",
    "@types/jasmine": "^2.2.30",
    "@types/jquery": "^3.2.0",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.5",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.1.5"
  }
}
`

**Comment by nileshyadav326** [comment] 2017-06-16 09:21
after deleting node_modules folder inside the angular-datatable module its works fine

**Comment by l-lin** [comment] 2017-06-19 11:13
Duplicate of #937.

**Closed by l-lin** 2017-06-19 11:13 UTC
